language: go
go:
  - 1.x

sudo: required

services:
  - docker

env:
  global:
    - secure: iyv/cQh7z/PjRyEySKELsd3L69AdRVlCnZrtozvM/Z+poeSnGtQIRLWgOw/Pe5ueNa/v7Wq2BKw1DHeTrgSnvNNt/uoTUWLY5UcHkPHQYm67DeB7CffSELgr8l6K7eBOqTn2Hu6mzPlmU6l3v8CBHg8uSJT6wv/XKqn2Ut74OBA7wCYRQyEXcnr26C7ytnN/XaaR/RPzXYyxoB6/l6aH1/PK9rt+btdBu4TPo5zZm6KVA8pp85KG7xfGjq6kNG+kDwFiaj6/DJmnxYKxsiyv/AsEtLmElxGKQQqCnOefbNwqSsdYDDqy5AikZ+ZfJQLRrLJzcHDzgREaiPCF0QVfGttcuX5AXpPkrBlKeixku91Dir4hebYAN7SWWwKktu8hqKTtQjc8eJMEbQVKTtk3yeRKqC4I8lUK6TBrJA7tnQpgq8w67Vm81P18UPPjKm6Wf6aCJEKSvrnVSwLvIrEN8q/ybrCupvvcze0l9nsQhJG/79BQX31mjZkqT9MdskgYgD3wrB2LexLYkw4BeyKOV1/fTyz7q82ocfEdNMHTnPKD4B2bXtl1Alx8wluIFjwOvy8QZ9Hopz+cNnfN/dOJcQn7hPQbjqIP7uumUTP2vVk3mtwPDKLYqfCeO1ZLwHClXog6Q2k8gb6mkEfVx6ygq/JxM5LkSnTdfyowLLTp7W0=
    - secure: gXwZlcsYZtbp4P/xABkXeBRHawfoUoBosS65s2fahC7xXJB3JPNsDNvvKMPz2sT4UIQ7bwsu2fJIUG3mFH2YjxvZsdKiQwNe+ghj+YpGPL6HPe08ZuxR+E84khK8zoSBtb80NdhxJvYVRJm0IaZK2dQx+BUtsSRTHNR859EdOL/MdVc0fgBRluar4jfq1MlVZH26AYZlZIdD40ZUmJXI18dsG+YSEXB+W4re5bpz5C++qdC3EiCghOPG1SOQRnMTG+6iyb3sWlyUlDfOa20uf3NPWc/pQCPRsKITenWuxd86DRYvhoknzGM4oxUtNymHv7n3fNZ/K49WDMzAhEd/kfNjOMc+CpLWtugqnSPpYIjKzDA8rMuvaIWjjgNcg6u5DV3uxohyJw/bIv23BB7i4b9C5mifymFMhkRqK01JbCMjIxRgzBspf3v3wvZrFntt2M/ic3A8BLxRLnaz76eKANlPejwhKkbvAYHqZQKQEywRyV6iKlfQjB2sbSty8bJW/vxXbigjFydIT4Af2CLzhU2XyT1vMXw8HPV1bKqJW1acpxlVDHrINcmKRhA//zEg0Z7a0fBlhmK/m5e7omrMDxxKFGDkDyKNy90WQZ+vh5Cxi2TWMs113ug/R91svAmAhUnUZV6dwx7dfxTbXVdiSxGnNbunNHNr4Pnbvdogyhk=
    - secure: j6S26JA04B+6bwr6detZauFu/UVPwmPhWvEcbVfNhvnNX3YKma8D2X9hvE6jDUOKeapiE/UsCHVgg8GFyPGu4M0ixUXUmu7HPNHFQ2x4a0tDgTyu0p9im5fPeJv4qbV+ORuE4Kvg54ZaZec3iBN94MegPVISpme86pMKdJui0cMEy/YPMUd1sh13h95WkESAshJd0n5AHO4xwD0NJjCK2waoA6ygvcwXhIpfTc9HsNgs6S8WVpRAfjkTj7+VGjoXTqov5g9d6SxBYvcJI/iBa0KgY7LhBRiC6AsE2WowVZeGDpnvL1nFsA2DQKcCC6Tv4VlP7jcyZMWcnELn8n6ucsHzT52bEhGu60KtZc5eohqW/1Ejb0riHvEJQMy875keBwIjuzERgxRaKEVGPQ3nZFu/rjEjHZSm0qi9+usb/vBcdKeu9fgjBeEDIkL5bE632P379VLI1bzzQS+dt+sPw1gqqDP+FJ1nED5r3g4zSPh4WqXAz4ohrX8CCqbxpy+Wjirer/yc7S+Bqx/iI2gKjdb6kwy1xePobFJyAMlOyHrwh5Tb6K23wJqVMoHL5mqG0Ent/3iXmvRS6PxsxwNPscyATUbazyGwXMj4oMWzcfs7yf0ADy/nbZLYUPVfHuysRZ6LAjptn+V8bdJ9A0rQmFUFDcP6VmMidxRlTcHR8yA=
    - secure: RynCQ7vWsIJUWVYWphTHRY0pI8b4EZVksaE6w8ghiFSvCzb6nvzGDkOafCXz7S9i1iWTOSPpnCW4Q977JKDxa8Godp1xuP8oWn1AmJpPltk/Wbc5qvLsAhIomXe9BDIzG90YDw7vQu5kjh+tbBhbnoKI7BM5BJ8r1oaHL3Vf7ooGWHI2NaEVnRQMNRij5OUSlRroy9bpeeJqibQBEzuPlb6Lsp4Vx4YWfsWpvhBgWzPyppYuMHQgA3tg7DlWeYL2NPgOOfr28VH8BHTUiCY/dO5BL4tGoM2C9xqUv1K2QOj1MXWkE3mjhOdSWgHMPx62ZBLgfbSBWflmLlnCZ9wMmrxIK3UKTSluMqRrQKTjp+e80cw287mRAQhj68XtELLQ3Pw3RobuEY0wnXkCvAkW+N2OPyq7/DK564ZHpkyuRMVibbmMP20EOoKG525WFM+WiZT8CSLwrY7BiP+1zurxnM1Bf6Zpte1ikHlHK7zJfZWPzvusMVoJGPfLlAF5KiG8RPzIRDAKqxtery+3JxBcqDeBeVh/3l1HrCgYkLKO/Bd41U2hSfqKPOWFBSV29n2m1K/m3RtgYc0r0M247uGZ+PGJzAZe/qXQoQJgW8OAoOFx/cFpqBI5rEIGbPjyX/ypFckcs3Vn2uQ430agsMcWj0rzfvVKKZS4Co4FcYp3OJw=

install:
  - make tools
  - pip install --user --upgrade sphinx semantic-version requests urllib3[secure]

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64  > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"

script:
  # Go1.10 is required to have proper use of coverprofile for multiple packages
  - TESTARGS="-coverprofile coverage.txt" make dist
  - cp coverage.txt c.out
  - "./docker_build.sh"

after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: bash deploy.sh
    on:
      all_branches: true
    skip_cleanup: true

  - provider: releases
    overwrite: true
    file_glob: true
    api_key:
      secure: N4G6gM4QaEUNn0DqgLazDeUh99VZzoKhbUF/v3sqvQLBLAQqL7k6pCfocuv8lLjhP4W1Xp+KpvUPC3jm8cWVApyuw0Ye9N4RBmpMNueujBO16beXXQf9oRWSCK7l9gcT++RjgIZNErcImQ99qObNB22XWzgVxvgRrqrsom+48qW/Vznh03Euv20xDBp96fvBkoTWKWW4nWZWg6sNx26c23vNZRPv49/sxa5brVdod7HD5x0QB3ZjeiChUQV7nOVfGJRtHiQuBZYGNOzStYUiLXClTB4xO5dywJ31pwLMJaOk2qLosHw+Kng5z1BghwzCfPhzMmJwVXdhUDqaVoXDRYMIHRyQFP48l3mYq0pw66JyoWyS82TnVjF4xvhbvUh7VW76kJWA15tyyM6kQ12o/14YG6GNgKp/qwRaTl5OiyH7G+8mt6ifHH/SIMkfpWQp4kTx4fHgrC6OYTuQe0YIvHt7SxRBAEXfj2wlosK7aLLzQ8OrVga/FDri85LfONE4U7anxpoDjAn8IzZrp2hFDyvZd6S7v7f6IusE0QJhSqDT1hsP9OTeKyrZSHYy9pVaZbmPKvmoz/xhx2hSEaa5gVACuPNMEfcy401SLunvrQqWQQq+qFdpTFRwCNtldWOJZeJlECZmJfz8CKbvYtJFixp+YvyjXzviO9RV83ZcY1U=
    file:
      - dist/yorc.tgz
      - dist/yorc-server-*-distrib.zip
      - pkg/docker-ystia-yorc-*.tgz
    skip_cleanup: true
    on:
      tags: true

addons:
  apt:
    packages:
    - latexmk
    - texlive-binaries
    - texlive-fonts-recommended
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
